#############################################
#!name=AppUnlock
#!desc=App解锁
#!author=lalifeier
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！
#############################################

[URL Rewrite]
# ✅ TikTok 解锁台灣地区
# hostname = *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com
(?<=_region=)CN(?=&) TW 307
(?<=&mcc_mnc=)4 2 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

[Map Local]

[Script]
# ✅BoxJS
# hostname = boxjs.com, boxjs.net
BoxJs = type=http-request, pattern=^https?:\/\/boxjs\.(com|net), script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js, requires-body=true, max-size=-1, timeout=60

# ✅SUB-STORE
# hostname = sub.store

sub-store-1.min = type=http-request, pattern=^https?:\/\/sub\.store\/((download)|api\/(preview|sync|(utils\/node-info))), script-path=https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-1.min.js, requires-body=true, max-size=-1, timeout=60

sub-store-0.min = type=http-request, pattern=^https?:\/\/sub\.store, script-path=https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-0.min.js, requires-body=true, max-size=-1, timeout=60

# ✅ AdGuard
# hostname = mobile-api.adguard.org
AdGuard = type=http-response, pattern=^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt\/(.*?), script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/AdGuard.js, requires-body=true, max-size=0

# ✅ 彩云天气
# hostname = biz.caiyunapp.com, biz.cyapi.com, biz.caiyunapp.cn, biz.cyapi.cn

彩云天气 = type=http-response, pattern=^http[s]?:\/\/biz\.(caiyunapp|cyapi)\.(com|cn)\/v2\/user.*$, script-path=https://raw.githubusercontent.com/zwf234/rules/master/js/caiyun.js, requires-body=true, max-size=-1, timeout=60

✅ 美图秀秀vip
# hostname = h5.xiuxiu.meitu.com, api.xiuxiu.meitu.com
美图秀秀vip = type=http-response, pattern=^https?:\/\/(h5|api)\.xiuxiu\.meitu\.com\/v\d\/(h\d\/vip|vip|user)\/, script-path=https://raw.githubusercontent.com/Moli-X/Resources/main/Script/MTxiuxiu/MeiTu.js, requires-body=true, max-size=-1, timeout=60

# ✅ 美图秀秀粉钻
# hostname =  api.xiuxiu.meitu.com
美图秀秀粉钻 = type=http-response, pattern=^https:\/\/api\.xiuxiu\.meitu\.com\/v1, script-path=https://raw.githubusercontent.com/Moli-X/Resources/main/Script/MTxiuxiu/MTxiuxiu.js, requires-body=true, max-size=-1, timeout=60

# ✅ Spotify(>=iOS15)
# 部分解锁premium, 音质不能设置为超高
# hostname = spclient.wg.spotify.com
spotify-json = type=http-request, pattern=^https?:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/, script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js

spotify-proto = type=http-response, pattern=^https?:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$, script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js, requires-body=true, binary-body-mode=true, max-size=0, script-update-interval=0

# ✅ TopWidgets
# hostname = top-widgets-api.xiaozujian.com
widgets = type=http-response, pattern=^https:\/\/top-widgets-api\.xiaozujian\.com\/api\/app\/config\/userConfig, script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/widgets.js, requires-body=true, max-size=-1, timeout=60

# ✅ XMind
# hostname = www.xmind.cn, www.xmind.net
xmind = type=http-response, pattern=https:\/\/www\.xmind\.cn\/\_res\/devices, script-path=https://raw.githubusercontent.com/zwf234/rules/master/js/xmind.js, requires-body=true, max-size=-1, timeout=60

# ✅ 微信100
# hostname = weixin110.qq.com, security.wechat.com
UnblockURLinWeChat = type=http-response, pattern=^https\:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% boxjs.com, boxjs.net, sub.store, mobile-api.adguard.org, biz.caiyunapp.com, biz.cyapi.com, biz.caiyunapp.cn, biz.cyapi.cn, h5.xiuxiu.meitu.com, api.xiuxiu.meitu.com, spclient.wg.spotify.com, top-widgets-api.xiaozujian.com, www.xmind.cn, www.xmind.net, weixin110.qq.com, security.wechat.com, *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com
